### ISSUE TITLE
Alternative syntax to mark the lines to be highlighted

### ISSUE THREAD

**Issue by shafayetShafee** [shafayetShafee/line-highlight#8]
A nice feature would be to mark the lines to be highlighted using a similar approach to Quarto [`code annotation`](https://quarto.org/docs/authoring/code-annotation.html#annotation-syntax) syntax or [Xaringaan's way to highlight lines](https://slides.yihui.org/xaringan/#30).

*It is originally suggested in #1*

**Comment by shafayetShafee** [comment]
@GShotwell, FYI, now it is possible to mark to be highlighted using `#<<` at the end of the line in code chunk from `line-highlight` version 1.2.0. For details [see here](https://github.com/shafayetShafee/line-highlight#using-highlight-marker-instead-of-line-numbers-added-in-version-120). Hopefully, this is what you are suggesting in #1.

**Comment by gshotwell** [comment]
Awesome!
